version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - 7006:3306
    networks:
    - test-app

#  dev:
#    container_name: nestjs_api_dev
#    image: nestjs-api-dev:1.0.0
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    command: npm run start
#    env_file:
#      - .env
#    #network_mode: host
#    ports:
#      - 4004:${MAIN_PORT}
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    restart: unless-stopped

networks:
  test-app: